databases:
  - name: backend
    plan: free
    databaseName: postgres
    user: mysite

services:
  - type: web
    plan: free
    name: backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn backend.asgi:application -k uvicorn.workers.UvicornWorker"    envVars:
      - key: postgresql://user:password@localhost:5432/dbname
        fromDatabase:
          name: postgres
          property: connectionString
      - key: postgresql://user:password@localhost:5432/dbname # to change
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
