databases:
  - name: backend
    plan: free
    databaseName: anitube_website_db
    user: mysite

services:
  - type: web
    plan: free
    name: backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn backend.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: "postgresql://anitube_website_db_user:rKwK56q345AO54tKDjVNPF2RKHVb59xv@dpg-cs25hre8ii6s739cf96g-a.oregon-postgres.render.com/anitube_website_db"
        fromDatabase:
          name: anitube_website_db
          property: connectionString
      - key: "postgresql://anitube_website_db_user:rKwK56q345AO54tKDjVNPF2RKHVb59xv@dpg-cs25hre8ii6s739cf96g-a.oregon-postgres.render.com/anitube_website_db" # to change
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
